// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAflAnEW0T33XCBe1SBHk4WGbr47If3XyI',
    appId: '1:200894546867:web:cffd82501125e6559401c6',
    messagingSenderId: '200894546867',
    projectId: 'autism-chat-bcdba',
    authDomain: 'autism-chat-bcdba.firebaseapp.com',
    storageBucket: 'autism-chat-bcdba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7liQt_99BT66_oHq-pgbsBplck1bVsOs',
    appId: '1:200894546867:android:60746b90c194e9e09401c6',
    messagingSenderId: '200894546867',
    projectId: 'autism-chat-bcdba',
    storageBucket: 'autism-chat-bcdba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Q_jaigo-kpYFjUPvBC-bdVyXQgIaxxU',
    appId: '1:200894546867:ios:7356057837108a999401c6',
    messagingSenderId: '200894546867',
    projectId: 'autism-chat-bcdba',
    storageBucket: 'autism-chat-bcdba.firebasestorage.app',
    iosBundleId: 'com.example.sanjeevani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5Q_jaigo-kpYFjUPvBC-bdVyXQgIaxxU',
    appId: '1:200894546867:ios:7356057837108a999401c6',
    messagingSenderId: '200894546867',
    projectId: 'autism-chat-bcdba',
    storageBucket: 'autism-chat-bcdba.firebasestorage.app',
    iosBundleId: 'com.example.sanjeevani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAflAnEW0T33XCBe1SBHk4WGbr47If3XyI',
    appId: '1:200894546867:web:92649b7fb82c46259401c6',
    messagingSenderId: '200894546867',
    projectId: 'autism-chat-bcdba',
    authDomain: 'autism-chat-bcdba.firebaseapp.com',
    storageBucket: 'autism-chat-bcdba.firebasestorage.app',
  );
}
